@api = http://localhost:3200/api/testigo

{{api}}

### add a product
POST http://localhost:3200/api/folios
Content-Type: application/json

{
"IdFolioCaso":"ABC123",
"IdFolioIPH":"ABC123",
"FechaArresto":"2022-12-12",
"HoraArresto":"Mon, 11 Oct 2021 20:48:13 GMT",
"FechaSalidaBarandilla":"2023-12-12",
"HoraSalidaBarandilla":"Mon, 11 Oct 2021 20:48:13 GMT",
"NombreCompletoInfractor":"Alfredo Leyva",
"TipoIdentificacion":1,
"NumeroIdentificacion":"197354682",
"Edad":30,
"Sexo":1,
"DomicilioCompleto":"Culiacan",
"EstadoCivil":2,
"Escolaridad":1,
"Ocupacion":"Developer"
}
### add a product
POST http://localhost:3200/api/dictamenmedico
Content-Type: application/json

{
"IdFolioCaso":"ABC123",
"IdFolioIPH":"ABC123",
"FechaDictamen":"2022-12-12",
"HoraDictamen":"Mon, 11 Oct 2021 20:48:13 GMT",
"MedicoCargo":"Porfirio Lopez",
"Resolucion":"Ese we está crazy"
}

### get product
{{api}}/1/2

### delete product 
DELETE {{api}}/5

### get count
{{api}}/count

### update
PUT {{api}}/11
Content-Type: application/json

{
    "IdFolioCaso":"123321",
"IdFolioIPH":"321123",
"FechaArresto":"2022-12-12",
"HoraArresto":"13:30:00",
"FechaSalidaBarandilla":"2023-12-12",
"HoraSalidaBarandilla":"14:00:00",
}

### 
PUT http://localhost:3200/api/dictamenpsic/3
Content-Type: application/json

 {
"id":3,
"personaCargo": "EMANUEL",
"resolucion": "DEV"
  }
###
POST http://localhost:3200/api/testigo
Content-Type: application/json

{
"IdFolioCaso":"F123",
"IdFolioIPH":"F123",
"NombreCompletoTestigo":"Captain American",
"DireccionTestigo":"New York, Torre Stark",
"OcupacionTestigo":"Avenger"
}

###
GET http://localhost:3200/api/testigo/F123/F123

### 
PUT http://localhost:3200/api/dictamenpsic/3
Content-Type: application/json

 {
"id":3,
"personaCargo": "EMANUEL",
"resolucion": "DEV"
  }




###
GET http://localhost:3200/api/reincidencia/123


###
POST http://localhost:3200/api/usuario
Content-Type: application/json

{
"Usuario":"5510",
"Password":"ABC123",
"NombreCompleto":"Emanuel Perez Cortes",
"Direccion":"Agustina Ramirez 2013 Los Mochis Sinaloa",
"Correo":"developermanfred@gmail.com",
"Telefono":"9541239889"
}
###
GET http://localhost:3200/api/



###
POST http://localhost:3200/api/login
Content-Type: application/json

{
"Usuario":"5510",
"Password":"123"
}
